CREATE TABLE tblTest1 (
	intID1_1 INT NOT NULL,
	intID1_2 INT NOT NULL,
	varTest VARCHAR NOT NULL,
	PRIMARY KEY (intID1_1, intID1_2)
);

CREATE TABLE tblTest2 (
	intID2_1 INT NOT NULL,
	intID2_2 INT NOT NULL,
	varTest VARCHAR NOT NULL,
	PRIMARY KEY (intID2_1, intID2_2),
	FOREIGN KEY(intID2_1, intID2_2) REFERENCES tblTest1(intID1_1, intID1_2)
);